server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/historia_clinica
    username: root
    password: Tija3663
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
